language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ls -al
  - ./gradlew build
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r web_app_application_wyt.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv web_app_application_wyt.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key:
      secure: $secret_access_key
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-wuyutin.me
    region: us-east-1
    skip_cleanup: true
    on:
     branch: assignment7
  - provider: codedeploy
    access_key_id: AKIAIKLAJ4TICD3P7GGQ
    bucket: code-deploy.csye6225-fall2017-wuyutin.me
    key: web_app_application_wyt.zip
    bundle_type: zip
    application: web_app_application_wyt
    deployment_group: web_app_application_wyt
    region: us-east-1
    secret_access_key:
      secure: $secret_access_key
    wait-until-deployed: true
    on:
     branch: assignment7

notifications:
  email:
    recipients:
      -wu.yutin@husky.neu.edu
      #travis build first
