language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war


after_success:
  - mkdir codedeploy
  - zip -r web_app_application_wyt.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv web_app_application_wyt.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIKLAJ4TICD3P7GGQ
    secret_access_key:
      secure: E0nMM+F5FSOTsMmuiZT4pRMx27paEZh4+or9DgnTRvteczA71tFturkx3zifiVv3fBs0YK60l7yTCEKp6FBvY3R8otc/cioeFJEfVzlgNnLB+mUCIVBtvhTw6AjKbImww0zCktL6cR12aKSYo5cCKtH3hDkjo6FNpSUZW74ETsUVUaHe+dSc2QKdAF3cgGKvQxWyqNRmgecfMJX6iBmNjgBRFNJdd3VGtdGQJRyMt/5f3qYilL/150SMrxIW2QxURyjC+obbzEc5v6AUiiLqop9PLDa/JDQR08FxmfXkU0oQUn+aWgogXRX190Y2zHTJyEH/88sNrNYBzN8JsJHyNpE7qODJpcuILrb79m5on/3SUSF4408+scqSpnNhe5V7yHmnjCVHb1f22wQjLbtbQna7UGALwUMvQq9z5sqFyouR3FWIz0THPdpLAYp2chQwNgdxHdbcapAS7VtKD27zpZ+u76ZQxEtKoQEwAr0FuaBFmDQsk0fqoTwDZbsx2hkMgiEhmmjkjdrhOxle/UYvR79vQ7QMMlo0kG2JZ/bF981CDNIXALajF8popKu7+BbA/6hAdUo/d/JQ6iMiWS2G4uIrdaj+L/5WvYisP5C0WTsPU9mswt0XEC00TqclJRl1//KCEbJe2i1EVZB79lA3U3iJWD2cMLlUkQuWWLRPlKs=
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-wuyutin.me
    region: us-east-1
    skip_cleanup: true
    on:
     branch: assignment7
  - provider: codedeploy
    access_key_id: AKIAIKLAJ4TICD3P7GGQ
    bucket: code-deploy.csye6225-fall2017-wuyutin.me
    key: web_app_application_wyt.zip
    bundle_type: zip
    application: web_app_application_wyt
    deployment_group: web_app_application_wyt
    region: us-east-1
    secret_access_key:
      secure: E0nMM+F5FSOTsMmuiZT4pRMx27paEZh4+or9DgnTRvteczA71tFturkx3zifiVv3fBs0YK60l7yTCEKp6FBvY3R8otc/cioeFJEfVzlgNnLB+mUCIVBtvhTw6AjKbImww0zCktL6cR12aKSYo5cCKtH3hDkjo6FNpSUZW74ETsUVUaHe+dSc2QKdAF3cgGKvQxWyqNRmgecfMJX6iBmNjgBRFNJdd3VGtdGQJRyMt/5f3qYilL/150SMrxIW2QxURyjC+obbzEc5v6AUiiLqop9PLDa/JDQR08FxmfXkU0oQUn+aWgogXRX190Y2zHTJyEH/88sNrNYBzN8JsJHyNpE7qODJpcuILrb79m5on/3SUSF4408+scqSpnNhe5V7yHmnjCVHb1f22wQjLbtbQna7UGALwUMvQq9z5sqFyouR3FWIz0THPdpLAYp2chQwNgdxHdbcapAS7VtKD27zpZ+u76ZQxEtKoQEwAr0FuaBFmDQsk0fqoTwDZbsx2hkMgiEhmmjkjdrhOxle/UYvR79vQ7QMMlo0kG2JZ/bF981CDNIXALajF8popKu7+BbA/6hAdUo/d/JQ6iMiWS2G4uIrdaj+L/5WvYisP5C0WTsPU9mswt0XEC00TqclJRl1//KCEbJe2i1EVZB79lA3U3iJWD2cMLlUkQuWWLRPlKs=
    wait-until-deployed: true
    on:
     branch: assignment7

notifications:
  email:
    recipients:
      -wu.yutin@husky.neu.edu
