language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - "./gradlew war"
  - gradle -Dtest.single=DemoApplicationTests test

after_success:
  - mkdir codedeploy
  - zip -r CSYE6225PROJECT.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv CSYE6225PROJECT.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIKPMVNS3GYS2UXIA
    secret_access_key:
      secure: V6bGILP+NERzHGdr/tJX12klZGwaqtdhDp11IPpISln4w7LNEIF/cU8aq184cp3rZScgrVI6R6qNrM9Lrq6JKoywgHiwxwkCRWfhmCnSCsnuFRlmAaQfu9US9nAkGA8+D9CrEqnx3z8KTb9iYQmYiYqQxoQfjYzt6wTFth4peh8P6CZV0jSo1/XpV5iaKlwAFCCjkKXFU7vO/2aWg319iUMzAAYh/NS2ryNK4jB6wV/q5FGebXVDU1PRPbjNSw2wGD0kNkpfIGNpunxQtIPCUvCbS0+poS91+E4JbZJxdl85SSiYk+5p7MLBuCJVnCzZHC1UpUduobPds9Xd2MDzXKo+Wdh7ttwHxt9FDVdLruQrJ4uXjp8RHsN5IKMeOxGbRt+CmvrZLGSGyRQ72fIB+IpiJn6DjqzQ00s6zv0fbvDA0lpmrK6TVIpD/l8MWZg14adYerNKJEA+KnAmcOx3VphEHDPC9QaZy7Z1bqaiJEl9WAmBrWBToWu6lpRfS3LyFhj9Ozhh7LCgxVH+bwQiLXlXbPAa7RiHl33pCbT16EYd26u8VsXUgHRTe13aCoLnGr7hGTbtMw5B2a6WfGGuGH5ujmDyHvy5TiQ7ulihMw271BEyc+ZVU1DliA2kaPBMfOZQQKqE1Z4kaPEakSLwQiJxMIo2lhMugiYufmb0ntw=
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-lijin3.me
    region: us-east-1
    skip_cleanup: true
    on:
     branch: assignment7
  - provider: codedeploy
    access_key_id: AKIAIKPMVNS3GYS2UXIA
    bucket: code-deploy.csye6225-fall2017-lijin3.me
    key: CSYE6225PROJECT.zip
    bundle_type: zip
    application: csye6225_application
    deployment_group: csye6225_application
    region: us-east-1
    secret_access_key:
     secure: V6bGILP+NERzHGdr/tJX12klZGwaqtdhDp11IPpISln4w7LNEIF/cU8aq184cp3rZScgrVI6R6qNrM9Lrq6JKoywgHiwxwkCRWfhmCnSCsnuFRlmAaQfu9US9nAkGA8+D9CrEqnx3z8KTb9iYQmYiYqQxoQfjYzt6wTFth4peh8P6CZV0jSo1/XpV5iaKlwAFCCjkKXFU7vO/2aWg319iUMzAAYh/NS2ryNK4jB6wV/q5FGebXVDU1PRPbjNSw2wGD0kNkpfIGNpunxQtIPCUvCbS0+poS91+E4JbZJxdl85SSiYk+5p7MLBuCJVnCzZHC1UpUduobPds9Xd2MDzXKo+Wdh7ttwHxt9FDVdLruQrJ4uXjp8RHsN5IKMeOxGbRt+CmvrZLGSGyRQ72fIB+IpiJn6DjqzQ00s6zv0fbvDA0lpmrK6TVIpD/l8MWZg14adYerNKJEA+KnAmcOx3VphEHDPC9QaZy7Z1bqaiJEl9WAmBrWBToWu6lpRfS3LyFhj9Ozhh7LCgxVH+bwQiLXlXbPAa7RiHl33pCbT16EYd26u8VsXUgHRTe13aCoLnGr7hGTbtMw5B2a6WfGGuGH5ujmDyHvy5TiQ7ulihMw271BEyc+ZVU1DliA2kaPBMfOZQQKqE1Z4kaPEakSLwQiJxMIo2lhMugiYufmb0ntw=
    wait-until-deployed: true
    on:
     branch: assignment7

notifications:
  email:
    recipients:
      - li.jin3@husky.neu.edu
