language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
  - gradle -Dtest.single=DemoApplicationTests test

after_success:
  - mkdir codedeploy
  - zip -r csye6225_application.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv csye6225_application.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIONLSFZA34G4XMJA
    secret_access_key:
      secure: QcWui2URFrZsmTYIQB97T0p+d58qFiXeWfneGKbAlgXkS8eY2V0FIANLSjVAazzMAqRdJMCwf9Y1kWg2LdEwJElwVwyn7oiSBPv0ihW+U1bBz18kvBZUydn8QVnz37zo+WG3Hc0lKxuxDz31VQxNij0hUvB2LK+FrtjEStrizBuMrWa5ja2tB7+e9K04VhIaVBBF2qxk9Ok79IIa1V2oIQQHdAF3DJlgSSFy273TYXlFksCUXzmDOrliRlhdHS3Q9ZmdUUb3NoQpiHcli8rWW3KdbYunRPfBuD3l1rY5avcF5uo2z/ItRE+I71IEVNSj3AzBhBIb9+IFzc8aSGghyZhmfLkNxzzq2tBGslLvznwSme/cKFKvbJ+iJPmIpOrRpzZtp6SNgcXPiqtSURbqz00VMBG1LrutD0zWdyh2xnK9LzARqV7sDMPeJqNb0hHcDAhhECK4aXUcyR6SXBXBxaOyzoyLqeKh2VGzI/ZOIkhWbFJC9KXO34/699KGO/heE3aiMTMqFdnZ18bYNtkmiACPEEglcGirLKho6Zbbz1k1ppEdTuiVu9PF2En2OLwI/3PaVCVJUbf7ees4uu2lLSr6/7dat3NmKm2ZoFRFR3necfywcmlbkx8MTYityuyRbEKUe6y1r4WS1L2zHb62BDezyRnqEb/sho00UNKUypQ=
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-lijin3.me
    region: us-east-1
    skip_cleanup: true
    on:
     branch: assignment7
  - provider: codedeploy
    access_key_id: AKIAIONLSFZA34G4XMJA
    bucket: code-deploy.csye6225-fall2017-lijin3.me
    key: csye6225_application.zip
    bundle_type: zip
    application: csye6225_application
    deployment_group: csye6225_application
    region: us-east-1
    secret_access_key:
     secure: QcWui2URFrZsmTYIQB97T0p+d58qFiXeWfneGKbAlgXkS8eY2V0FIANLSjVAazzMAqRdJMCwf9Y1kWg2LdEwJElwVwyn7oiSBPv0ihW+U1bBz18kvBZUydn8QVnz37zo+WG3Hc0lKxuxDz31VQxNij0hUvB2LK+FrtjEStrizBuMrWa5ja2tB7+e9K04VhIaVBBF2qxk9Ok79IIa1V2oIQQHdAF3DJlgSSFy273TYXlFksCUXzmDOrliRlhdHS3Q9ZmdUUb3NoQpiHcli8rWW3KdbYunRPfBuD3l1rY5avcF5uo2z/ItRE+I71IEVNSj3AzBhBIb9+IFzc8aSGghyZhmfLkNxzzq2tBGslLvznwSme/cKFKvbJ+iJPmIpOrRpzZtp6SNgcXPiqtSURbqz00VMBG1LrutD0zWdyh2xnK9LzARqV7sDMPeJqNb0hHcDAhhECK4aXUcyR6SXBXBxaOyzoyLqeKh2VGzI/ZOIkhWbFJC9KXO34/699KGO/heE3aiMTMqFdnZ18bYNtkmiACPEEglcGirLKho6Zbbz1k1ppEdTuiVu9PF2En2OLwI/3PaVCVJUbf7ees4uu2lLSr6/7dat3NmKm2ZoFRFR3necfywcmlbkx8MTYityuyRbEKUe6y1r4WS1L2zHb62BDezyRnqEb/sho00UNKUypQ=
    wait-until-deployed: true
    on:
     branch: assignment7

notifications:
  email:
    recipients:
      -li.jin3@husky.neu.edu
