language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
  - gradle -Dtest.single=DemoApplicationTests test

after_success:
  - mkdir codedeploy
  - zip -r csye6225_application.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv csye6225_application.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAJOQLKWGMK7WCARDA
    secret_access_key:
      secure: aKmsczTlMTlu+dAe7SbNyqnnkjb9RMp1ZhuiNje/eoiK0LQq01i42WqaV0ZAlkZV7CoG8EtrftO5EwE9PriQlBWToGmgj9sSQte+6M50TZV4ZL/3F4R1ZneECIsAEH2CitseXg6YZAsiuncRaq7AeQpaB2gNSd3Ml0iekLa7IA+ZF5R3nzWP6mBTDenVqcMl7GvqD+KOhhMEbAP7Znb8CVC3n5IMrJfLqr2tbnVULWx1Wi2MH8JlVRGou1d0OtLqXhapngLpiD8uZ1liZHuGvGLziMIGvRZWPsK9d1w00tGvZl45nAa2HY1UDzvjfnaGTE/7jUZJsLnzRVJpxzaiDpyb49VwMgHTVx/j0RDpp4KHBJrkO1bX6KX20nmAF1Cw03cJnkCA9v7vTYlcymj7ettUrW9MkmoaKIH6aouM9g8ZXS6Ex3j79zmu4yeVjoXRdVH+peEvadj1tdOAHZmQc23iZW0D2hpX+4sGyNIBx5loHL4Gzoihh91M6naSIR6VbcTC7HkRP33QCv5yA9Qwf0T2Dt2UZwwoz/IjYjgZJhrgrGwuIsPAp+0bL4Zh+n+zqdQ9jYYFr1+70Nzgfdr8PTA4Q7/et4Ncrbr8f8q2ozNGBGNwOtF4Qc9nwqxH02uirUXeBy6WZaLa4U9l43e3WV26cmB3QiOzJRb4Sh/NK2g=
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-lijin3.me
    region: us-east-1
    skip_cleanup: true
    on:
     branch: assignment7
  - provider: codedeploy
    access_key_id: AKIAJOQLKWGMK7WCARDA
    bucket: code-deploy.csye6225-fall2017-lijin3.me
    key: csye6225_application.zip
    bundle_type: zip
    application: csye6225_application
    deployment_group: csye6225_application
    region: us-east-1
    secret_access_key:
     secure: aKmsczTlMTlu+dAe7SbNyqnnkjb9RMp1ZhuiNje/eoiK0LQq01i42WqaV0ZAlkZV7CoG8EtrftO5EwE9PriQlBWToGmgj9sSQte+6M50TZV4ZL/3F4R1ZneECIsAEH2CitseXg6YZAsiuncRaq7AeQpaB2gNSd3Ml0iekLa7IA+ZF5R3nzWP6mBTDenVqcMl7GvqD+KOhhMEbAP7Znb8CVC3n5IMrJfLqr2tbnVULWx1Wi2MH8JlVRGou1d0OtLqXhapngLpiD8uZ1liZHuGvGLziMIGvRZWPsK9d1w00tGvZl45nAa2HY1UDzvjfnaGTE/7jUZJsLnzRVJpxzaiDpyb49VwMgHTVx/j0RDpp4KHBJrkO1bX6KX20nmAF1Cw03cJnkCA9v7vTYlcymj7ettUrW9MkmoaKIH6aouM9g8ZXS6Ex3j79zmu4yeVjoXRdVH+peEvadj1tdOAHZmQc23iZW0D2hpX+4sGyNIBx5loHL4Gzoihh91M6naSIR6VbcTC7HkRP33QCv5yA9Qwf0T2Dt2UZwwoz/IjYjgZJhrgrGwuIsPAp+0bL4Zh+n+zqdQ9jYYFr1+70Nzgfdr8PTA4Q7/et4Ncrbr8f8q2ozNGBGNwOtF4Qc9nwqxH02uirUXeBy6WZaLa4U9l43e3WV26cmB3QiOzJRb4Sh/NK2g=
    wait-until-deployed: true
    on:
     branch: assignment7

notifications:
  email:
    recipients:
      -li.jin3@husky.neu.edu
